### ISSUE TITLE
Mixed name and company

### ISSUE THREAD

**Issue by dfoody** [RateGravity/parse-full-name#20]
I'm not sure if you consider this out-of-scope for this library, but often people have their company name with their own name.

Some examples: `T. J. Watson, IBM Corp.`, `T. J. Watson, CEO, IBM Corp.`.
There are other more "wordy" variations as well:  `T. J. Watson of IBM Corp.`, `T. J. Watson from IBM Corp.`.

What are your thoughts on whether these are things you want this library to handle?
Thanks!

**Comment by chris-pardy** [comment]
@dfoody I believe this is out of scope. This library is being primarily to parse a full name input into it's component parts for apis and other systems that want names submitted as first/last
