### ISSUE TITLE
nameParts[j] should be updated to namePartWords[j]

### ISSUE THREAD

**Issue by art-ortega** [RateGravity/parse-full-name#23]
https://github.com/RateGravity/parse-full-name/blob/9bc524845becd893fc0a05934518dbfaed0f3efa/index.js#L73

Line 73 and Line 74

**Comment by chris-pardy** [comment]
Please provide a description of the issue that is being caused by this bug rather than a simple fix.

**Comment by chris-pardy** [comment]
Resolved in release 1.2.6
